### ISSUE TITLE
Return model instance from ActiveType object

### ISSUE THREAD

**Issue by glaucocustodio** [makandra/active_type#104]
Hi folks!

Suppose I have the following ActiveType class:

```ruby
class PartnerForm < ActiveType::Record[Partner]
end
```

In my controller, I am using pundit to authorize, but instead of a Partner object, I try to pass a PartnerForm instance to `authorize` method like:

```ruby
before_action :set_partner, only: [:show, :edit, :update, :destroy]
before_action :authorize_partner

def set_partner
  @partner = ActiveType.cast(Partner.find(params[:id]), PartnerForm)
end

def authorize_partner
  authorize @partner || Partner
end
```

Since `ActiveType.cast(Partner.last, PartnerForm) == Partner.last` returns `false`, I can't compare a `PartnerForm` instance with a `Partner` instance in my policy.

I would like to know if there is a method l can call on an instance of `PartnerForm` to return my model instance like:

```ruby
ActiveType.cast(Partner.last, PartnerForm).model == Partner.last # true
```

I guess such method does not exist yet, but I think it can be useful, given it is not the first time I need it.

Would you accept a PR?

```ruby
# this is the workaround I am using today which I'd like to avoid
Partner.find(ActiveType.cast(Partner.last, PartnerForm).id) == Partner.last 
```

**Comment by triskweline** [comment]
I'm afraid we're not familiar with Pundit. Can you show the code where you compare a `PartnerForm` with a `Partner`? Is the `==` in your own code or in Pundit's code?

I would prefer not having to keep the casted `Partner` around if possible. Since we're `dup`ing all its internal state in `ActiveType.cast()` this would double the memory required.

Maybe we can override `==` so it returns true when an extended record is compared to base class record? Or maybe add a second method for that kind comparison? @kratob

**Comment by glaucocustodio** [comment]
The comparison is done by me through `==`.

I don't think it is reasonable to make the `==` operator return true, because the PartnerForm instance may have been modified from the original active record instance (I am using in a form).

I think just a syntax sugar which simply does `Model.find(id)` would be enough, this way I could do something like `partner_form.model == partner`.

**Comment by kratob** [comment]
I'd be hesitant to override `==`, too, but maybe we could add a `#same_record_as?(...)` method? That seems to be preferrable anyways, since you don't really need to make another DB query, just to check that it's the same record.

**Comment by glaucocustodio** [comment]
My main concern is not with the comparison, but rather in getting the db-version of the record.

Imagine I have a form with currency fields, the values are inputed like `2.500,00` but I keep these values in decimal field on db like `2500,00`. After create, I would like to broadcast a message with the db-version of the record, so, I gotta do `Model.find(id)` to get it.

Would be nice to have a method to do this boilerplate code for me.

**Comment by glaucocustodio** [comment]
Yeah, I know I can do this. But would be nice to have something like this in the gem. We can warn users the consequences of calling a `model` method.

**Comment by kratob** [comment]
Sorry, but I don't feel this to be generally useful enough, and it's easy to add if a user needs it, so I'd rather not have it in `ActiveType` itself.
