### ISSUE TITLE
Allow to change an association's model

### ISSUE THREAD

**Issue by andyl** [makandra/active_type#11]
I'd like to create associations that return ActiveType objects - something like the example below:

``` ruby
class User < ActiveRecord::Base
  has_many :messages
end
class Message < ActiveRecord::Base
  belongs_to :user
end
class User::AsTexting < ActiveType::Record[User]
  has_many :texting_messages, class_name: 'Message::AsTexting'
end
class Message::AsTexting < ActiveType::Record[Message]
  belongs_to :texting_user, class_name: 'User::AsTexting'
end
```

Will this work?  Is there a better way to build Rails-like associations to ActiveType objects?

**Comment by mhenrixon** [comment]
How would I replace single table inheritance with form objects for updates? Use some sort of factory method to cast to a specific form? That would still be saving the type then but I could seriously simplify what is stored in the type column I guess.

Anyone have any better suggestions?

**Comment by henning-koch** [comment]
@mhenrixon You can cast AR instances to another class by using [`#becomes`](http://apidock.com/rails/ActiveRecord/Persistence/becomes)

**Comment by kratob** [comment]
ActiveType 1.2.0 now includes `.change_association`.
