### ISSUE TITLE
Ruby 2.7 deprecation warnings

### ISSUE THREAD

**Issue by vkhalzov** [makandra/active_type#123]
I have deprecation warnings in my app:
* active_type-1.4.1/lib/active_type/record_extension/inheritance.rb:72: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
* active_type-1.4.1/lib/active_type/record_extension/inheritance.rb:68: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

Stack:
Ruby 2.7.1
Rails 6.0.3.2
active_type 1.4.1

**Comment by kevinhq** [comment]
It seems those warnings have been fixed in 1.4.2

I don't see it with this stack:

ruby 2.7.2
rails (6.0.3.4)
active_type (1.4.2)

**Comment by kratob** [comment]
All of these warnings go away on Ruby 2.7.2. Since, as far as I'm aware, Rails itself has the same issues on Ruby 2.7.1 I'd consider this good enough. I've added tests for 2.7.2 and see no warnings at all.
