### ISSUE TITLE
Calling to_yaml on an ActiveType::Object does not serialize correctly

### ISSUE THREAD

**Issue by chriscz** [makandra/active_type#127]
Calling `to_yaml` on a `ActiveType::Object` does not serialize its attributes whereas `to_json` does and works as expected. 

I am willing to PR a fix for this by overriding the `init_with`, `encode_with` methods as defined in [`ActiveRecord::Core`](https://github.com/rails/rails/blob/fe76a95b0d252a2d7c25e69498b720c96b243ea2/activerecord/lib/active_record/core.rb#L318) (used by Psych) and adding a Yaml encoder similar to `ActiveModel::AttributeSet::YAMLEncoder` to serialize the `virtual_attributes` field instead of `@attributes` as is currently done by the implementation in ActiveRecord.

**Example**
```ruby
class Person < ActiveType::Object
  attribute :name
end
p = Person.new(name: "Chris")
p.to_yaml
# => "--- !ruby/object:Person\nconcise_attributes: []\nnew_record: true\nactive_record_yaml_version: 2\n"
```

**Comment by kratob** [comment]
Hi @chriscz. Sounds reasonable, feel free to send a PR.
