### ISSUE TITLE
Helper Convenience Method

### ISSUE THREAD

**Issue by andyl** [makandra/active_type#13]
Draper uses a convenience method #h to invoke a view helper.  It would be great if ActiveType used the same convention.  IMHO prefixing with #h is better than directly including the large number of methods in `ActionController::Base.helpers`.

``` ruby
module ActiveType
  module Helpers
    def h
      ActionController::Base.helpers
    end
  end
end

h.puralize(2, "word") 
```

**Comment by henning-koch** [comment]
We don't want to depend on `actionpack`, so this shouldn't be on by default.

What we could do is provide the module above so people could `include` this in their ActiveType classes when we needed.
