### ISSUE TITLE
Ruby 3 breaks change_association

### ISSUE THREAD

**Issue by pjo336** [makandra/active_type#136]
I haven't completely narrowed down why this is, but when calling the `has_many` method through the use of `public_send(existing_association.macro, association_name, new_scope, original_options.merge(new_options))`, we now receive the error message:
```
ArgumentError:
  wrong number of arguments (given 3, expected 1..2)
```

This works fine in Ruby 2.7.2. I'm currently trying to debug a bit using monkey patching, but I'm not finding anything helpful

**Comment by triskweline** [comment]
Delegating control to another method is a tire fire in Ruby 2.7+.

Maybe `ruby2_keywords` can help here:
- https://ruby-doc.org/core-3.0.0/Module.html#method-i-ruby2_keywords
- https://github.com/ruby/ruby2_keywords

**Comment by pjo336** [comment]
Haven't quite figured out how that works, but working on it!

**Comment by judithroth** [comment]
We added Ruby 3 support with 1.7.0. Therefore, this should work now.
