### ISSUE TITLE
ActiveType is loosing its changed_association starting with version 1.8.0

### ISSUE THREAD

**Issue by denzelem** [makandra/active_type#147]
While upgrading a Rails application that uses `active_type` (From `1.3.2` to `1.10.0`) , I noticed that `change_association` does not work the same way as before. The breaking change was in 6a623c5c003fc5bb414ba58ee320b2a53fe9b399.

Example c50aca69fc7f801446c526921bd434c2831c54e7:

```
class Car < ActiveRecord::Base
  has_one :steering_wheel
end

class SteeringWheel <ActiveRecord::Base
  belongs_to :car
end

class ExtendedCar < ActiveType::Record[Car]
  class ExtendedSteeringWheel < SteeringWheel
  end

  change_association :steering_wheel, class_name: 'ExtendedCar::ExtendedSteeringWheel'
end

car = Car.create!
SteeringWheel.create!(car: car)

extended_car = ActiveType::Util.cast(car, ExtendedCar)
expect(extended_car.steering_wheel).to be_a(ExtendedCar::ExtendedSteeringWheel)
``` 

```
Failure/Error: expect(extended_car.steering_wheel).to be_a(ExtendedCar::ExtendedSteeringWheel)
expected #<SteeringWheel id: 1, car_id: "1"> to be a kind of ExtendedCar::ExtendedSteeringWheel(id: integer, car_id: string)
```

Is there anything I missed or is this something that was accidentally changed this way? From the commit message it is not 100% clear to me, what the background for this change was.

**Comment by kratob** [comment]
I believe the change was intended to not drop any unsaved records in an association while casting, but the interaction with `change_association` was missed. This is a bit unfortunate, I'm not sure about a good solution that can handle both cases.

**Comment by judithroth** [comment]
The change from version 1.8.0 was reverted so `change_association` should now work as it used to do :)
