### ISSUE TITLE
Methods on ActiveRecord::AttributeMethods::Dirty cause MutationAfterCastError

### ISSUE THREAD

**Issue by KD6-3** [makandra/active_type#170]
If you call a method like `attribute_was` on your original model object, then this method call causes a `MutationAfterCastError`. 

`attribute_was` is not changing the model so this method call shouldn't cause this error.

Of course you can easily avoid this error by calling methods like `attribute_was` only on the casted `ActiveType` object. 

https://github.com/makandra/active_type/blob/master/lib/active_type/util/unmutable_attributes.rb
https://api.rubyonrails.org/v5.1/classes/ActiveRecord/AttributeMethods/Dirty.html#method-i-attribute_was

**Comment by kratob** [comment]
Thanks for reporting. Is fixed in 2.3.2.
