### ISSUE TITLE
Casting drops the `strict_loading` state of an ActiveRecord object

### ISSUE THREAD

**Issue by makmic** [makandra/active_type#181]
I was recently faced with N+1 queries which surprised me as I had `strict_loading` enabled in every controller.
Digging into the issue I noticed that active_type drops the `strict_loading` state after casting an object:

```rb
user = User.strict_loading.find(3)
user.strict_loading? # true

casted_user = ActiveType.cast(user, User::Form)
casted_user.strict_loading? # false
```

A quick workaround would be to re-enable it after casting:
```rb
casted_user = ActiveType.cast(user, User::Form).tap(&:strict_loading!) if user.strict_loading?
casted_user.strict_loading? # true
```

I think it would make sense to fix this in the gem itself, WDYT?

**Comment by kratob** [comment]
Yes, that's definitely something ActiveType should fix.

**Comment by makmic** [comment]
Okay. :+1: 

I just had another look at all boolean methods of an example AR-instance. We should probably check all of those while fixing the issue above:

```
 :strict_loading?,
 :strict_loading_n_plus_one_only?,
 :readonly?,
 :frozen?,
```
