### ISSUE TITLE
Using `attribute` class macro with specific class as the type

### ISSUE THREAD

**Issue by mecampbellsoup** [makandra/active_type#20]
After bumping to Rails 4.2, my code here:

```ruby
module Flyblade::GiftCard
  class CreditCard < ActiveType::Object
    attribute :cvc,            :varchar
    attribute :user,           Flyblade::GiftCard::User
  end
end
```

... now generates the following error/server output:

```
Started GET "/gift_cards/new" for ::1 at 2014-12-24 11:12:33 -0500
Processing by GiftCardsController#new as HTML
D, [2014-12-24T11:12:34.086022 #28239] DEBUG -- :   User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id
" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 9477]]
E, [2014-12-24T11:12:34.113763 #28239] ERROR -- : PG::SyntaxError: ERROR:  syntax error at or near "User"
LINE 1: SELECT 'Flyblade::GiftCard::User'::regtype::oid
               ^
CONTEXT:  invalid type name "Flyblade::GiftCard::User"
: SELECT 'Flyblade::GiftCard::User'::regtype::oid
Completed 500 Internal Server Error in 37ms
** [Bugsnag] No API key configured, couldn't notify

PG::SyntaxError - ERROR:  syntax error at or near "User"
LINE 1: SELECT 'Flyblade::GiftCard::User'::regtype::oid
               ^
CONTEXT:  invalid type name "Flyblade::GiftCard::User"
```

Any ideas @henning-koch? If you can point me in the direction of the potential break I'd be happy to look into the source code.

**Comment by kratob** [comment]
I'm not sure why it worked before, but the `attribute` macro is not meant to accept arbitrary types, only symbols that would also be meaningful in something like a migration. It is only used to do automatic type casting (i.e. the string `"100"` to the number `100`), but not for custom types.

If you don't need type casting, simply use
```
   attribute :user
```

**Comment by henning-koch** [comment]
I believe Virtus has some functionality that if you set an attribute to a class, and that class has a constructor with one argument, it uses that constructor for typecasting.

However, we don't have that feature (yet) in ActiveType. If it worked before it was an unintended side effect. Sorry for the confusion!
