### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by andyl** [makandra/active_type#27]
It would be great to review a list of changes before upgrading to the latest version of `ActiveType`.  

Could you add a changelog?

**Comment by bryanrite** [comment]
Seconded!

**Comment by mhenrixon** [comment]
:+1: I'd prefer that over going through the code changes trying to figure it out what changed and if it affects me. Love the gem and the work you put into it!

**Comment by kratob** [comment]
Noted. I'll add one for future changes.

**Comment by mattbrictson** [comment]
@andyl would you agree this issue can be closed now that #39 has been merged?

**Comment by andyl** [comment]
Yes - this issue can be closed!  Thank you @mattbrictson
