### ISSUE TITLE
Rails 4.2.0 ActiveType::Object#save fails with ActiveModel::MissingAttributeError can't write unknown attribute ``

### ISSUE THREAD

**Issue by mattbrictson** [makandra/active_type#31]
*Update: this affects Rails 4.2.0 only. Rails 4.2.1 does not seem to be affected.*

Scenario:

* Class `MyForm` inherits from `ActiveType::Object`
* `@myform` has validation errors
* Controller calls `@myform.save`

Expectation:

* `@myform.save` should return `false`, since the object is invalid

Bug:

Instead, I get this exception:

```
ActiveModel::MissingAttributeError can't write unknown attribute ``
```

Cause:

1. When `save` is called and validation fails, ActiveRecord calls `restore_transaction_record_state`
2. This in turn calls `write_attribute(self.class.primary_key, restore_state[:id])`
3. But for an ActiveType::Object, primary_key is `nil`
4. `write_attribute` doesn't expect a nil attribute name, so it blows up

Workaround:

I've worked around the bug by explicitly declaring a `MyForm.primary_key`. I'm not sure if this has other consequences, but it seems to work:

```
def self.primary_key
  :id
end
```

Here's the relevant stack trace:

```
ActiveModel::MissingAttributeError - can't write unknown attribute ``:
  activerecord (4.2.0) lib/active_record/attribute.rb:124:in `with_value_from_database'
  activerecord (4.2.0) lib/active_record/attribute_set.rb:39:in `write_from_user'
  activerecord (4.2.0) lib/active_record/attribute_methods/write.rb:74:in `write_attribute_with_type_cast'
  activerecord (4.2.0) lib/active_record/attribute_methods/write.rb:56:in `write_attribute'
  activerecord (4.2.0) lib/active_record/attribute_methods/dirty.rb:92:in `write_attribute'
  activerecord (4.2.0) lib/active_record/transactions.rb:393:in `restore_transaction_record_state'
  activerecord (4.2.0) lib/active_record/core.rb:514:in `update_attributes_from_transaction_state'
  activerecord (4.2.0) lib/active_record/core.rb:508:in `sync_with_transaction_state'
  activerecord (4.2.0) lib/active_record/persistence.rb:86:in `new_record?'
  activerecord (4.2.0) lib/active_record/persistence.rb:99:in `persisted?'
  actionview (4.2.0) lib/action_view/helpers/form_helper.rb:456:in `apply_form_for_options!'
  actionview (4.2.0) lib/action_view/helpers/form_helper.rb:434:in `form_for'
```

**Comment by vevisystems** [comment]
We were experienced the same problem, the suggested workaround works. Thanks for the hint

**Comment by vevisystems** [comment]
Overwritting save also works:



  def save
    valid?
  end

**Comment by treznick** [comment]
+1

**Comment by henning-koch** [comment]
I'm afraid I can't reproduce the issue:

```
2.1.2 :001 > class Foo < ActiveType::Object
2.1.2 :002?>     attribute :flag, :boolean
2.1.2 :003?>     validates_presence_of :flag
2.1.2 :004?>   end
 => [ActiveModel::Validations::PresenceValidator] 
2.1.2 :005 > 
2.1.2 :006 >   
2.1.2 :007 >   foo = Foo.new(flag: false)
 => #<Foo > 
2.1.2 :008 > foo.save
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
 => false 
```

**Comment by mattbrictson** [comment]
@henning-koch Sorry, my explanation was a bit misleading. The call to `save` works fine. The exception is encountered when the form is rendered again in the view after validation fails. Here's the stack trace for clarification. Notice the problem originates with `form_for` being called in the view.

```
ActiveModel::MissingAttributeError - can't write unknown attribute ``:
  activerecord (4.2.0) lib/active_record/attribute.rb:124:in `with_value_from_database'
  activerecord (4.2.0) lib/active_record/attribute_set.rb:39:in `write_from_user'
  activerecord (4.2.0) lib/active_record/attribute_methods/write.rb:74:in `write_attribute_with_type_cast'
  activerecord (4.2.0) lib/active_record/attribute_methods/write.rb:56:in `write_attribute'
  activerecord (4.2.0) lib/active_record/attribute_methods/dirty.rb:92:in `write_attribute'
  activerecord (4.2.0) lib/active_record/transactions.rb:393:in `restore_transaction_record_state'
  activerecord (4.2.0) lib/active_record/core.rb:514:in `update_attributes_from_transaction_state'
  activerecord (4.2.0) lib/active_record/core.rb:508:in `sync_with_transaction_state'
  activerecord (4.2.0) lib/active_record/persistence.rb:86:in `new_record?'
  activerecord (4.2.0) lib/active_record/persistence.rb:99:in `persisted?'
  actionview (4.2.0) lib/action_view/helpers/form_helper.rb:456:in `apply_form_for_options!'
  actionview (4.2.0) lib/action_view/helpers/form_helper.rb:434:in `form_for'
```

**Comment by mattbrictson** [comment]
@henning-koch Here is a minimal Rails app the demonstrates the issue:

https://github.com/mattbrictson/active-type-31

To run the demo:

1. Check out the repo
2. `bin/setup`
4. `bin/rails server`
5. Visit <http://localhost:3000>

**Comment by jhirbour** [comment]
+1

**Comment by mattbrictson** [comment]
This is fixed in activerecord 4.2.1. I upgraded my test case from Rails 4.2.0 to 4.2.1 and the bug is no longer present.

**Comment by v-sh** [comment]
Thanks for the hint.

**Comment by thatandyrose** [comment]
Was about to shoot myself dead, thanks for this! :gun: :hankey:

**Comment by kvanderd** [comment]
+1

**Comment by mattbrictson** [comment]
Everyone who +1'd this issue: does upgrading to Rails 4.2.1 solve the problem for you? I.e. does it eliminate the need for the `def self.primary_key` workaround?

**Comment by kvanderd** [comment]
Upgrading to Rails 4.2.1 solved this problem for me. Thank you for opening this issue and providing a solution.

**Comment by v-sh** [comment]
Yes, I just upgrade.

**Comment by mattbrictson** [comment]
@kvanderd @v-sh thanks for confirming! Glad to hear it worked for you, too.

**Comment by henning-koch** [comment]
ActiveType `0.3.5` now refuses to load with ActiveRecord 4.2.0.
