### ISSUE TITLE
Wrong time because of timezone

### ISSUE THREAD

**Issue by TheWudu** [makandra/active_type#33]
Hi!

We have a problem with the gem converting times into the current timezone.

When passing "2015-03-02T08:23:18Z" as time, which already includes timezone: Z (UTC), the time is converted into a wrong time according the servers time-zone.

This happens inside the gem when conversion is performed for time types:

(Time.zone is set to Australia/Darwin)
2.1.0 :086 > ActiveSupport::TimeWithZone.new(nil, Time.zone, Time.parse("2015-03-02T08:23:18Z"))
 => Mon, 02 Mar 2015 08:23:18 ACST +09:30 

If we pass UTC the output is correct. So the 

2.1.0 :085 >   ActiveSupport::TimeWithZone.new(nil, ActiveSupport::TimeZone.new("UTC"), Time.parse("2015-03-02T08:23:18Z"))
 => Mon, 02 Mar 2015 08:23:18 UTC +00:00 

Time.parse itself does the right thing, considering the Z.:

Time.parse("2015-03-02T08:23:18Z")
 => 2015-03-02 08:23:18 UTC

Any hints how to prevent this?

Best regards,
Wudu

**Comment by henning-koch** [comment]
Please confirm that this is not an issue with classes inheriting from `ActiveRecord::Base`. ActiveType only mimics ActiveRecord behavior.

**Comment by sch1zo** [comment]
I've made a minimal example which demonstrates the problem
https://gist.github.com/sch1zo/e9e69bfe8c0a49f7760c

**Comment by sch1zo** [comment]
you can have a look at our current fix here https://github.com/runtastic/active_type/commit/e382ddb9975c28e6893c2a12bae7795a8a050dea

It works for all kind of iso8601 strings and Time objects(which already have a timezone). It does not work for strings like "2010-10-01 12:15" where no timezone is given. Our fix will in this case always assume the time is UTC and not like AR localtime (which works for us as we either have proper timezone info or use UTC).

**Comment by jamesfernandes** [comment]
Just wanted to note here that, even though this ticket is still open, the issue has been resolved (#94) as of v0.7.2, released 2017-07-31. That made my day!

**Comment by triskweline** [comment]
Thanks for following up @jamesfernandes !
