### ISSUE TITLE
Nests_one vs. has_one

### ISSUE THREAD

**Issue by Mingan** [makandra/active_type#40]
I have a regular `ActiveRecord::Base` model with has_one association, which has a defined `class_name` because the associated model is namespaced. Then I defined an `ActiveType::Record` with the original model and called `nests_one` with the associated model and defined scope (again with the fully namespaced class name of the associated model).

I can work with the `ActiveType::Record` just fine, but when I try to access the associated model I get `nil` even when it exists (doing the same for the underlying model works fine), there's no query in the log.

I've tried moving the `has_one` call around and it doesn't really matter where I put it or if it's there at all. Which leads me to assume, that ActiveType somehoew redefines the method for accessing the associated model by name but I didn't find any way to specify properties of the association by `nests_one`.

I would like to keep the association at the core model, because it is read in other contexts and is an integral part of the model. But I need the access via nested attributes only in one context (calling accepts_nested_attributes in the underlying model seems to work), which would lead me to using nests_one in the  `ActiveType::Record` to indicate, that this type of manipulation is specific to that interface.

I assume, it's somehow my fault, but just can't figure out what am I doing wrong.

**Comment by mattbrictson** [comment]
If you are using `ActiveType::Record` for a database-backed attribute, then you have the full `ActiveRecord::Base` behavior at your disposal. Therefore I think you should be using `accepts_nested_attributes_for` instead of `nests_one`. The latter is only for virtual attributes.

**Comment by Mingan** [comment]
Sure, it makes much more sense. I'm not sure where my head was.
