### ISSUE TITLE
Association writer method name

### ISSUE THREAD

**Issue by bradrobertson** [makandra/active_type#41]
This *somewhat* goes along with [this issue](https://github.com/makandra/active_type/issues/11). Basically, I want my public api to allow for something like this:

```ruby
class ParentForm < ActiveType::Record[Parent]
  attribute :whatever
  nests_many :children, scope: -> {ChildForm}
end
class ChildForm < ActiveType::Record[Child]
  validates :name, presence: true
end
```
Such that when I create a parent form, I could pass in an object like this:
```ruby
{
  whatever: "something",
  children: [
    {name: 'one'},
    {name: 'two'}
  ]
}
```

And I'd have the `children` array all casted to `ChildForm` objects. Basically what I want is to NOT enforce the `_attributes` suffix on a nested child writer key.

I can see from [the code](https://github.com/makandra/active_type/blob/master/lib/active_type/nested_attributes/builder.rb#L35) that this currently isn't possible, but I'm looking for advice on how to achieve this.

I don't like the `_attributes=` prefix requirement as I don't really think a public API endpoint should need to be aligned with the html form that *might* be used in conjunction with it. For a public API perspective, I just want to pass in `children`, not `children_attributes`.

Any suggestions?

**Comment by henning-koch** [comment]
You could implement your own `children=` method that translates your desired API to the one used by ActiveType.

**Comment by dbourguignon** [comment]
I had the same concern, and I ended up using something like

```ruby
    def children=(children)
      self.children_attributes = children
    end
```

**Comment by bradrobertson** [comment]
ugh, that worked. A little embarrassed I didn't try that. Thanks!
