### ISSUE TITLE
before_destroy not working

### ISSUE THREAD

**Issue by olegantonyan** [makandra/active_type#45]
Hi! I have a problem with `active_type 0.4.0`.
`before_destroy` (also `after_destroy`) callback never called  

``` ruby
class Membership < ActiveType::Object
  before_save { puts 'hello wonderful world' }
  before_destroy { puts 'goodbye cruel world' }
end
```

``` ruby
Membership.new.save 
# => hello wonderful world
# => true
Membership.new.destroy 
# => #<Membership:0x007fefda4456e8> {}
```

**Comment by henning-koch** [comment]
We honestly never considered someone would use any action other than `save`.

@kratob Do you think this is something we should support? If not, we should probably raise an error in `#destroy` to prevent confusion.

**Comment by kratob** [comment]
The issue also occurs for `after_create` callbacks; and at least those should probably work. I would prefer supporting all callbacks, to raising on `destroy`.

Fix is most likely to manually run the callback chain in `ActiveType::NoTable` (compare https://github.com/rails/rails/blob/master/activerecord/lib/active_record/callbacks.rb).

**Comment by mattbrictson** [comment]
By definition a `NoTable` model is not persistent, so part of the confusion is what do things like `create`, `update`, and `destroy` even mean in this case? I prefer the simplicity of supporting only `save` callbacks. However it can be frustrating to define e.g. `before_update` or `after_destroy` and wonder why it isn't being called. Perhaps more documentation and/or a warning/exception when an unsupported callback is declared would help clear things up.

Just my 2¢.

**Comment by henning-koch** [comment]
I'm afraid I don't understand the use case of all the people using actions other than `save`. Why would one destroy an object, since we cannot create it?

Some goes for @mattbrictson 's issue about [`after_commit`](https://github.com/makandra/active_type/issues/47). Why do you expect a "commit" to happen?

I always thought of `ActiveType::Object`s as one-verb actions, triggered by `save` (actually more `run` but we kept `save` because of the AR heritage).

I'm a little concerned that trying to emulate all the actions that only make sense with a database will limit our ability to change the implementation under the hood in the future.

**Comment by olegantonyan** [comment]
Well, here is my use case.
``` ruby
# controllers/api/v2/base_controller.rb
class Api::V2::BaseController < BaseController
  def result object, method = :save
    method = :destroy if caller[0][/`.*'/][1..-2] == 'destroy'
    if object.send method
      def object.to_json(options) ''; end # don't want to return the whole object on create/update
      respond_with object, location: (method == :destroy ? nil : object_url(object))
    else
      raise UnprocessableEntityError.new(object.errors.full_messages.join(', '))
    end
  end

  def object_url object
    url = polymorphic_url(object)
  rescue NoMethodError
    url = "there is no show route for #{object.class.name} object"
  end
end
```
Then in my specific api controllers
``` ruby
class Api::V2::ReportsController < Api::V2::BaseController
  def create
    report = Report.new(report_params)
    result report
  end

  def update
    report = Report.find(params[:id])
    report.assign_attributes report_params
    result report
  end

  def destroy
    report = Report.find(params[:id])
    result report
  end

end
```
As long as `object` passed to `Api::V2::BaseController.result` quacks like `ActiveRecord::Base` it works perfectly. But what if I want to pass some object with no database table? Like Membership mentioned in first post:
``` ruby
class Api::V2::UserGroups::MembershipsController < Api::V2::BaseController
  before_action :set_user_group
  before_action :set_membership

  def create
    @membership.flexible_price = User::Group::FlexiblePrice.find(params[:price_id])
    result @membership
  end

  def destroy
    result @membership
  end

  private

  def set_user_group
    @user_group = User::Group.find(params[:user_group_id])
  end

  def set_membership
    @membership = User::Group::Membership.new user: current_user, group:  @user_group
  end

end
```
The `User::Group::Membership` class has no corresponding database table since it's not has_many: :through join model, but rather simple object which encapsulates all logic related to user's group membership. At some point it can mutate into join model with db table, but now my domain logic restricts user has_one and_only_one group.

The whole point of this is to have uniform interface to the models, so controllers and friends don't have to know if it's ActiveRecord-supercharged or not.

**Comment by henning-koch** [comment]
That's interesting, thanks.

For some reason I would have gone with two separate classes `Membership::Create` and `Membership::Destroy`, each with their `save` method.

I get your point about *"so controllers and friends don't have to know if it's ActiveRecord-supercharged or not"*.

**Comment by kratob** [comment]
Closing as stale, please reopen if you want to work on this.
