### ISSUE TITLE
Could you please support methods which defined in ActiveRecord::QueryMethods

### ISSUE THREAD

**Issue by frozenfung** [makandra/active_type#56]
Hi, Koch

As title, could you please support useful methods like `includes` , `select` and `group` and so on which are defined in `ActiveRecord::QueryMethods` ?

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/query_methods.rb

thanks ;)

Best,
Fung

**Comment by kratob** [comment]
Hi Fung,

`ActiveType::Record` is backed by the database, inherits from `ActiveRecord::Base`, and so does already support these methods.

`ActiveType::Object` is not backed by a database, and so it does not support them.
