### ISSUE TITLE
unnecessary repetition in generated SQL

### ISSUE THREAD

**Issue by cisolarix** [makandra/active_type#62]
```
require 'rails/all'
require 'active_type'

ActiveRecord::Base.establish_connection(
  adapter:  "mysql2",
  host:     "localhost",
  username: "root",
  password: "",
  database: "xxx"                     
)

class Company < ActiveRecord::Base
  has_many :employees
end

class Human < ActiveRecord::Base
end

class Employee < Human
end

class Engineer < ActiveType::Record[Employee]
end

class Manager < ActiveType::Record[Employee]
end

Employee.descendants.map(&:sti_name) 
# => ["Employee", "Employee", "Employee", "Employee"]

Company.first.employees.to_sql  
# => "SELECT `humans`.* FROM `humans` WHERE `humans`.`type` IN ('Employee', 'Employee', 'Employee', 'Employee', 'Employee') AND `humans`.`company_id` = 1"

```

Though the generated SQL works as expected, it still doesn't look good to me. Any suggestions?

**Comment by cisolarix** [comment]
`sti_name` has been overrided in [this file](https://github.com/makandra/active_type/blob/master/lib/active_type/extended_record/inheritance.rb#L19-L21)

Array is not `.uniq`ed in [this file](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/inheritance.rb#L196)

**Comment by kratob** [comment]
You're right, this SQL is definitely not very nice.

On the other hand, I don't see a way of fixing this without monkey-patching Rails, which I'd really rather avoid. Since this doesn't really break anything, I think I'd rather keep it as it is.

**Comment by henning-koch** [comment]
I agree. Let's not maintain monkey patches for multiple versions of Rails. Closing this as won't fix.

**Comment by cisolarix** [comment]
One of the workarounds is put code listed below in `Employee` model:
```
def self.descendants
 []
end
```

But I don't know if this snippet has any drawbacks or not. @kratob
