### ISSUE TITLE
type cast on writing virtual attribute

### ISSUE THREAD

**Issue by v-sh** [makandra/active_type#63]
I'm not sure if it's a bug.
Use code like this:
```
class CallSession < ActiveType::Object
  attribute :start_date, :datetime
end

def create_session
  Time.use_zone('UTC') { CallSession.new(start_date: '2016-02-24 10:46:43')}
end

Time.zone = 'Moscow'
session = create_session
session.start_date 
=> Wed, 24 Feb 2016 10:46:43 MSK +03:00
```
The problem is: when I assign value, attribute_writer only invalidate cache and set raw value, and actual type_caster runs only when I try to read value.
In this case moment when type_caster runs is important.

**Comment by henning-koch** [comment]
I believe ActiveRecord delays typecasting when a value is read. This is because of performance considerations. ActiveType only mimics ActiveRecord's behavior.

**Comment by v-sh** [comment]
@henning-koch , actually I have tested usual activerecord model and it works as expected(use utc). May be, in ActiveRecord there is a special workaround for it.
