### ISSUE TITLE
new_record? is not correct when model save callback raise an exception

### ISSUE THREAD

**Issue by paicha** [makandra/active_type#68]
### Model

```
class User < ActiveType::Object
  attribute :name
  validates_presence_of :name

  save do
    raise ActiveRecord::Rollback
  end

end

```
### Console

```
pry(main)> user = User.new
=> #<User name: nil>
pry(main)> user.new_record?
=> true
pry(main)> user.save
=> false
pry(main)> user.new_record?
=> true
pry(main)> user.name = 'sunny'
=> "sunny"
pry(main)> user.save
   (0.2ms)  BEGIN
   (0.2ms)  ROLLBACK
=> true
pry(main)> user.new_record?
=> false
```
### Issue

The `user.new_record?` should be `true` when `save` callback raise an exception.

**Comment by henning-koch** [comment]
I don't believe we even specified the result of `#new_record?` for a model that is not backed by a database table row. Would we leave this unspecified or change it to "#save successed without validation errors or rollbacks" @kratob ?

**Comment by kratob** [comment]
I would prefer if `#new_record?` simply always returned `true` for `ActiveType::Object`. This seems to be most consistent with current behavior.

**Comment by kratob** [comment]
I believe this has nothing to do with the exception. `.new_record?` seems to return `false` after `save` on Rails 5, but not on Rails 3 or 4.

**Comment by kratob** [comment]
Closing as stale, please reopen if you want to work on this.
