### ISSUE TITLE
ActiveRecord not configured correctly

### ISSUE THREAD

**Issue by elct9620** [makandra/active_type#72]
Hi,

I have some problem about `ActiveRecord::Base.belongs_to_required_by_default` config.

According the issue https://github.com/rails/rails/issues/27777 and https://github.com/rails/rails/issues/23589#issuecomment-229247727, this problem needs to resolved by gem.

Is there have any plan to fix it?

**Comment by kratob** [comment]
I've just release 0.6.2 which should fix this issue.
