### ISSUE TITLE
Caching classes generated by ActiveType::Record.[]

### ISSUE THREAD

**Issue by jkr2255** [makandra/active_type#80]
By current implement of `ExtendedRecord`, A new class is generated each time `ActiveType::Record.[]` is invoked.

It might be a problem in some use cases:

* Using `ActiveType:Rrecord.[]` inside loop yields generation of many classes
* Always `ActiveType::Record[SomeRecord] != ActiveType::Record[SomeRecord]`, it may confuse classification.

Caching generated classes will solve these problems.

**Comment by triskweline** [comment]
I think that caching developer classes in a gem global would cause havoc with Rails' autoloading.

For what purpose are you calling `ActiveType::Record.[]` that often?
