### ISSUE TITLE
Partial rollback with two nested attributes

### ISSUE THREAD

**Issue by cerdiogenes** [makandra/active_type#84]
Giving this class:

```ruby
class Event::LandingPageForm < ActiveType::Object
  nests_one :user
  nests_one :event
end
```

And this Event class:

```ruby
class Edition < ApplicationRecord
  after_create :method_raising_exception

  private

  def method_raising_exception
    raise 'rollback only edition'
  end
end
```

When I call save in an instance of Event::LandingPageForm, only the event is rolled back. The expected behavior is to have everything rolled back, right?

**Comment by cerdiogenes** [comment]
I forgot to say, I'm using activerecord-5.1.0.rc2

**Comment by triskweline** [comment]
Yes, the whole save to LandingPageForm and all its nested records should be rolled back.

We haven't tested ActiveType against ActiveRecord 5.1 yet.

Does this behavior occur with activerecord 5.1.1?

**Comment by cerdiogenes** [comment]
I will try to update my application ASAP and give a feedback.

**Comment by cerdiogenes** [comment]
Sorry for the long time, but I can't reproduce the bug anymore in ActiveRecord 5.1.4, so I'm closing this, thanks!
