### ISSUE TITLE
NotImplementedError when checking for uniqueness

### ISSUE THREAD

**Issue by Ichaelus** [makandra/active_type#90]
The following class raises a NotImplementedError:

```Ruby
class User::SignUp < ActiveType::Object
  attribute :email, :string
  validates :email, uniqueness: true
end
```
The same error occurs when setting uniqueness to `{case_sensitive: false}`.

Best,
Michael

**Comment by foobear** [comment]
`ActiveType::Object` is not backed by a database record, so it can't validate uniqueness.

It looks like you want to define a form model. If you inherit from `ActiveType::Record[User]`, everything should be fine. :)
